"""
agents/verifier.py — Agent 5: Verifier

WHAT THIS AGENT DOES:
    Performs the final quality gate. Compares the original document against
    the modernized output, scores the conversion on multiple dimensions,
    and produces a formal sign-off report. This is the last agent in the
    pipeline and the last line of defense before the output is trusted.

BEDROCK PARALLEL:
    This mirrors the Verification Agent in your professional COBOL pipeline.
    That agent runs the generated test suite against both the original COBOL
    and the converted Oracle code to confirm functional equivalence.

    Here we can't run code, but we do the equivalent for documents:
    - Did all rules survive the conversion?
    - Did all procedures survive intact and in order?
    - Did any meaning change, even subtly?
    - Is the plain language actually clearer, or did it introduce ambiguity?

MODEL CHOICE — claude-opus-4-6:
    This is the only agent that uses Opus instead of Sonnet. The Verifier
    needs the highest reasoning capability because it must:
    1. Hold two large documents in mind simultaneously
    2. Detect subtle meaning changes (not just missing text)
    3. Make a judgment call on whether the output is trustworthy

    In your Bedrock pipeline, you'd make the same choice: use the most
    capable model for the final verification step, and cheaper/faster
    models for the earlier transformation steps.

CONFIDENCE SCORE:
    The score (0-100) is a weighted judgment across four dimensions:
    - Completeness  (40%): Did all rules, procedures, terms make it through?
    - Accuracy      (30%): Is the meaning preserved without distortion?
    - Clarity       (20%): Is the rewrite actually clearer than the original?
    - Structure     (10%): Is the document well-organized and navigable?

    A score of 85+ is a passing grade. Below 70 should trigger a rejection
    and a rerun. The Verifier also produces a binary sign_off (true/false)
    which is the formal go/no-go for the pipeline output.
"""

import json
import anthropic
from models.pipeline_state import PipelineState


SYSTEM_PROMPT = """You are a senior quality assurance auditor specializing in government document modernization.

You will receive:
1. The original legacy document (source of truth)
2. The modernized rewrite produced by an AI pipeline
3. The verification questions generated by a previous agent

Your job is to produce a formal verification report that determines whether the modernized
document is a faithful, complete, and clear rewrite of the original.

SCORING DIMENSIONS (total 100 points):
- Completeness (40 pts): Every rule, procedure, deadline, role, and term from the original is present
- Accuracy (30 pts): No meaning has been changed, distorted, or introduced that wasn't in the original
- Clarity (20 pts): The rewrite is genuinely clearer and more readable than the original
- Structure (10 pts): The document is well-organized with clear headers and logical flow

SIGN-OFF CRITERIA:
- sign_off: true  → Score >= 85 AND no critical accuracy issues
- sign_off: false → Score < 85 OR any critical accuracy issue found

OUTPUT FORMAT — return ONLY valid JSON, no markdown, no explanation:

{
  "confidence_score": 0,
  "score_breakdown": {
    "completeness": 0,
    "accuracy": 0,
    "clarity": 0,
    "structure": 0
  },
  "sign_off": false,
  "recommendation": "APPROVE | APPROVE_WITH_NOTES | REJECT",
  "findings": [
    {
      "severity": "info | warning | critical",
      "category": "completeness | accuracy | clarity | structure",
      "finding": "string — specific, actionable observation under 30 words"
    }
  ],
  "questions_assessment": {
    "answerable_from_rewrite": 0,
    "total_questions": 0,
    "unanswerable": ["Q001", "Q005"]
  },
  "summary": "string — 2-3 sentence plain-language summary of the verification result"
}
"""


def run(state: PipelineState, client: anthropic.Anthropic) -> PipelineState:
    """
    Agent 5: Verifier

    Compares the original document against the modernized output, scores
    the conversion, and produces a formal sign-off report.

    Args:
        state:  Pipeline state. We read source_document_text,
                modernized_document, and verification_questions.
                We write verification_report.
        client: Shared Anthropic client. Uses claude-opus-4-6 for this agent.

    Returns:
        Updated PipelineState with verification_report populated.
    """

    print("\n" + "=" * 60)
    print("  AGENT 5 — VERIFIER")
    print("=" * 60)

    if not state.source_document_text:
        raise ValueError("Verifier requires the original source document.")
    if not state.modernized_document:
        raise ValueError("Verifier requires the modernized document from Agent 2.")

    question_count = len(state.verification_questions) if state.verification_questions else 0
    print(f"  Input: original doc + modernized doc + {question_count} verification questions")
    print(f"  Model: claude-opus-4-6 (highest reasoning for final gate)")

    state.stage = "verifying"

    user_message = f"""Produce a verification report for this document modernization.

ORIGINAL DOCUMENT:
─────────────────────────────────────────────────────
{state.source_document_text}
─────────────────────────────────────────────────────

MODERNIZED DOCUMENT:
─────────────────────────────────────────────────────
{state.modernized_document}
─────────────────────────────────────────────────────

VERIFICATION QUESTIONS (generated from the original's semantic map):
{json.dumps(state.verification_questions, indent=2) if state.verification_questions else "None available"}

For each verification question, determine whether it can be answered
correctly using only the modernized document. List any that cannot
in the questions_assessment.unanswerable array.
"""

    print("\n  Calling Claude (Opus)... ", end="", flush=True)

    message = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": user_message
            }
        ]
    )

    raw_response = message.content[0].text
    print("done.")

    # ── Parse JSON ─────────────────────────────────────────────────────────────
    try:
        report = json.loads(raw_response)
    except json.JSONDecodeError:
        cleaned = raw_response.strip()
        if cleaned.startswith("```"):
            cleaned = "\n".join(cleaned.split("\n")[1:])
        if cleaned.endswith("```"):
            cleaned = "\n".join(cleaned.split("\n")[:-1])
        report = json.loads(cleaned)

    state.verification_report = report
    state.stage = "verified"

    # ── Save report to reports/ directory ─────────────────────────────────────
    from pathlib import Path
    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)
    report_path = reports_dir / f"{state.pipeline_id}_verification_report.json"
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    # ── Results summary ────────────────────────────────────────────────────────
    score = report.get("confidence_score", 0)
    sign_off = report.get("sign_off", False)
    recommendation = report.get("recommendation", "UNKNOWN")
    breakdown = report.get("score_breakdown", {})
    findings = report.get("findings", [])
    q_assessment = report.get("questions_assessment", {})

    criticals = [f for f in findings if f.get("severity") == "critical"]
    warnings = [f for f in findings if f.get("severity") == "warning"]
    unanswerable = q_assessment.get("unanswerable", [])

    # Score bar
    bar_filled = int(score / 5)
    bar = "█" * bar_filled + "░" * (20 - bar_filled)
    score_color = "✓" if score >= 85 else ("⚠" if score >= 70 else "✗")

    print(f"\n  ┌─ VERIFICATION REPORT ──────────────────────────────┐")
    print(f"  │                                                      │")
    print(f"  │  Confidence Score : {score_color} {score}/100                        │")
    print(f"  │  [{bar}]          │")
    print(f"  │                                                      │")
    print(f"  │  Completeness : {breakdown.get('completeness', '?'):>3}/40                            │")
    print(f"  │  Accuracy     : {breakdown.get('accuracy', '?'):>3}/30                            │")
    print(f"  │  Clarity      : {breakdown.get('clarity', '?'):>3}/20                            │")
    print(f"  │  Structure    : {breakdown.get('structure', '?'):>3}/10                            │")
    print(f"  │                                                      │")
    sign_off_str = "✓ SIGNED OFF" if sign_off else "✗ NOT SIGNED OFF"
    print(f"  │  {sign_off_str:<52}│")
    print(f"  │  Recommendation : {recommendation:<35}│")
    print(f"  └──────────────────────────────────────────────────────┘")

    if unanswerable:
        print(f"\n  ⚠  {len(unanswerable)} verification question(s) unanswerable from rewrite: {unanswerable}")

    if criticals:
        print(f"\n  ✗ Critical findings ({len(criticals)}):")
        for f in criticals:
            print(f"    [{f['category']}] {f['finding']}")

    if warnings:
        print(f"\n  ⚠ Warnings ({len(warnings)}):")
        for f in warnings:
            print(f"    [{f['category']}] {f['finding']}")

    info_findings = [f for f in findings if f.get("severity") == "info"]
    if info_findings:
        print(f"\n  ℹ Notes ({len(info_findings)}):")
        for f in info_findings:
            print(f"    [{f['category']}] {f['finding']}")

    print(f"\n  Summary: {report.get('summary', '')}")
    print(f"\n  📄 Full report saved: {report_path}")

    usage = message.usage
    print(f"\n  Token usage: {usage.input_tokens} in / {usage.output_tokens} out")

    return state
